// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc9000.FRC2015Java.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc9000.FRC2015Java.Robot;
import org.usfirst.frc9000.FRC2015Java.RobotMap;

/**
*
*/
public class  DriveForward extends Command {
	double Kp = 0.05;// was 0.05 whith a delay of 0.004

   public DriveForward() {
       // Use requires() here to declare subsystem dependencies
       // eg. requires(chassis);

       // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
       this.setTimeout(1.0d);  // going to drive forward for 3 seconds
   }

   // Called just before this Command runs the first time
   protected void initialize() {
   	RobotMap.driveGyro.reset();
   }

   // Called repeatedly when this Command is scheduled to run
   protected void execute() {
   	double angle = RobotMap.driveGyro.getAngle(); // get current heading
       double motorPower = 0.2;
       
       RobotMap.driveRobotDrive.drive(motorPower, -angle*Kp); // drive towards heading 0
       //Timer.delay(0.004);

   }

   // Make this return true when this Command no longer needs to run execute()
   protected boolean isFinished() {
       return this.isTimedOut();
   }

   // Called once after isFinished returns true
   protected void end() {
   	// Nothing needs to be done
   }

   // Called when another command which requires one or more of the same
   // subsystems is scheduled to run
   protected void interrupted() {
   	// Nothing needs to be done
   }
}
