// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc9000.MyRobot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Encoder driveLeftWheelPosition;
    public static Encoder driveRightWheelPosition;
    public static Gyro driveGyro;
    public static SpeedController driveLeftMotors;
    public static SpeedController driveRightMotors;
    public static RobotDrive driveRobotDrive;
    public static Encoder clawClawMotorBuiltInEncoder;
    public static SpeedController clawClawMotor;
    public static Encoder elevatorElevatorEncoder;
    public static SpeedController elevatorElevatorMotor;
    public static Relay lightsSpikeForLights;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveLeftWheelPosition = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("Drive", "LeftWheelPosition", driveLeftWheelPosition);
        driveLeftWheelPosition.setDistancePerPulse(1.0);
        driveLeftWheelPosition.setPIDSourceParameter(PIDSourceParameter.kRate);
        driveRightWheelPosition = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("Drive", "RightWheelPosition", driveRightWheelPosition);
        driveRightWheelPosition.setDistancePerPulse(1.0);
        driveRightWheelPosition.setPIDSourceParameter(PIDSourceParameter.kRate);
        driveGyro = new Gyro(0);
        LiveWindow.addSensor("Drive", "Gyro ", driveGyro);
        driveGyro.setSensitivity(0.007);
        driveLeftMotors = new Talon(0);
        LiveWindow.addActuator("Drive", "LeftMotors", (Talon) driveLeftMotors);
        
        driveRightMotors = new Talon(1);
        LiveWindow.addActuator("Drive", "RightMotors", (Talon) driveRightMotors);
        
        driveRobotDrive = new RobotDrive(driveLeftMotors, driveRightMotors);
        
        driveRobotDrive.setSafetyEnabled(true);
        driveRobotDrive.setExpiration(0.1);
        driveRobotDrive.setSensitivity(0.5);
        driveRobotDrive.setMaxOutput(1.0);
        

        clawClawMotorBuiltInEncoder = new Encoder(6, 7, false, EncodingType.k4X);
        LiveWindow.addSensor("claw", "ClawMotorBuiltInEncoder", clawClawMotorBuiltInEncoder);
        clawClawMotorBuiltInEncoder.setDistancePerPulse(1.0);
        clawClawMotorBuiltInEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        clawClawMotor = new Talon(3);
        LiveWindow.addActuator("claw", "ClawMotor", (Talon) clawClawMotor);
        
        elevatorElevatorEncoder = new Encoder(4, 5, false, EncodingType.k4X);
        LiveWindow.addSensor("Elevator", "ElevatorEncoder", elevatorElevatorEncoder);
        elevatorElevatorEncoder.setDistancePerPulse(1.0);
        elevatorElevatorEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        elevatorElevatorMotor = new Talon(2);
        LiveWindow.addActuator("Elevator", "ElevatorMotor", (Talon) elevatorElevatorMotor);
        
        lightsSpikeForLights = new Relay(1);
        LiveWindow.addActuator("Lights", "SpikeForLights", lightsSpikeForLights);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
